[package]
name = "cw721-updatable"
version = "1.1.0"
authors = [
    "Ethan Frey <ethanfrey@users.noreply.github.com>",
    "Orkun Külçe <orkun@deuslabs.fi>",
    "Drew Taylor <drew.taylor@philabs.xyz>",
]
edition = "2018"
description = "Definition and types for the CosmWasm-721 NFT interface"
license = "Apache-2.0"
repository = "https://github.com/archid-protocol/cw721-updatable"
homepage = "https://archid.app"

[dependencies]
cw-utils = "1.0.3"
cosmwasm-std = { version = "1.5.3" }
schemars = "0.8.10"
serde = { version = "1.0.140", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.5.3" }
